'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.18408
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("campusmap.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _1421199215_location_alt_512() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1421199215_location-alt-512", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property aclake() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("aclake", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property acplant() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("acplant", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property adminbldg() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("adminbldg", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property akshara() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("akshara", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property aseb() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("aseb", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property athfield() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("athfield", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property audicircle() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("audicircle", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property auditorium() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("auditorium", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property bank() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bank", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property barak() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("barak", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property basky() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("basky", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property bblock() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bblock", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property biotechnology() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("biotechnology", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property brahmo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("brahmo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property campMap() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("campMap", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cblock() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cblock", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cc() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cc", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cee() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cee", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cet() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cet", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cfe() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cfe", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property chem() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("chem", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property chemical() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("chemical", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property chs() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("chs", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cif() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cif", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property civil() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("civil", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cnt() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cnt", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property confhall() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("confhall", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property core1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("core1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property core2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("core2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property core3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("core3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property core4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("core4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cric() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cric", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cse() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cse", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property dblock() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("dblock", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property design() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("design", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property dhansiri() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("dhansiri", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property dibang() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("dibang", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property dihing() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("dihing", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property dir() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("dir", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property eblock() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("eblock", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property EEE() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("EEE", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property football() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("football", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property guesth() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("guesth", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property hockey() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("hockey", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property hospital() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("hospital", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property hss() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("hss", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property iitg_large() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("iitg_large", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property kameng() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("kameng", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property kapili() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("kapili", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property kv() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("kv", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property kvgate() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("kvgate", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property lake() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("lake", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property layer4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("layer4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property library() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("library", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property lt() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("lt", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property main_gate() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("main_gate", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property manas() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("manas", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property market_complex() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("market_complex", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property married() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("married", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property math() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("math", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property mch() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mch", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property mech() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mech", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property phy() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("phy", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property pool() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pool", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property power() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("power", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property sac() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sac", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property serp() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("serp", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property siang() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("siang", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property subansiri() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("subansiri", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property tc() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tc", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property tennis() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tennis", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property treasure_map1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("treasure_map1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property treasure_map11() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("treasure_map11", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property treasure_map12() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("treasure_map12", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property umiam() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("umiam", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property viewpoint() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("viewpoint", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property volley() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("volley", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property water() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("water", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property workshop() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("workshop", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 1266|ac|379|admin|338|akshara|568|aseb|580|athletic|490|audi|372|barak|598|bt|343|brahmo|506|bblock|435|cblock|347|environment|350|energy|346|chem|350|cet|351|ce|307|facultyHall|405|cc|362|conference|355|cricket|456|cse|350|dd|349|dibang|458|dihing|532|dblock|298|dblock2|297|dblock3|257|eee|353|eblock|273|eblock2|211|football|456|guesthouse|414|hockey|458|hospital|462|hss|307|guestlake|449|iitglake|396|kameng|595|kapili|458|kv|456|manas|491|marketComplex|232|married|497|mech|315|phy|307|siang|458|subansiri| [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property XData() As String
            Get
                Return ResourceManager.GetString("XData", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 780|ac|436|admin|367|akshara|208|aseb|165|athletic|279|audi|344|barak|390|bt|522|brahmo|462|bblock|80|cblock|98|environment|508|energy|532|chem|494|cet|455|ce|508|facultyHall|113|cc|394|conference|344|cricket|349|cse|467|dd|438|dibang|449|dihing|422|dblock|135|dblock2|202|dblock3|255|eee|481|eblock|222|eblock2|295|football|281|guesthouse|208|hockey|316|hospital|178|hss|478|guestlake|228|iitglake|346|kameng|367|kapili|421|kv|488|manas|422|marketComplex|209|married|218|mech|445|phy|532|siang|390|subansiri|272 [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property YData() As String
            Get
                Return ResourceManager.GetString("YData", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
